#!/bin/sh

playerctl pause

B='#00000000'  # blank
C='#ffffff22'  # clear ish
#D='#ff00ffcc'  # default
D='#16a085ee'
#T='#ee00eeee'  # text
T='#16a085ee'  # text
W='#880000bb'  # wrong
V='#222D31aa'  # verifying

i3lock \
--insidever-color=$C   \
--ringver-color=$V     \
\
--insidewrong-color=$C \
--ringwrong-color=$W   \
\
--inside-color=$B      \
--ring-color=$D        \
--line-color=$B        \
--separator-color=$D   \
\
--verif-color=$T        \
--wrong-color=$T        \
--time-color=$T        \
--date-color=$T        \
--layout-color=$T      \
--keyhl-color=$V       \
--bshl-color=$W        \
\
--screen 1            \
--blur 8              \
--indicator	      \
--clock               \
--time-str="%H:%M:%S"  \
--date-str="%A %d %m %Y" \
--wrong-text="Nope!"   \

# --veriftext="Drinking verification can..."
# --textsize=20
# --modsize=10
# --timefont=comic-sans
# --datefont=monofur
# etc

