#!/bin/bash
monitor=$(xrandr --listactivemonitors | tail -n +2 | sed -E 's/:.* /: /' | rofi -dmenu -p "Display notifications on screen " -no-custom -lines 3 -width 500 | sed -E 's/ ([0-9]):.*/\1/')
[ -z "$monitor" ] && exit 0
killall dunst
dunst -mon $monitor &
notify-send "Dunst" "Notification will be displayed on this screen"

