#!/bin/sh
LAPTOP="eDP"
LAPTOP_RES="1920x1080"
DESKTOP="DisplayPort-4"
DESKTOP_RES="2560x1440"
DESKTOP_RATE="75.00"
case "$1" in
    clone)
	xrandr --output $LAPTOP --primary --output $DESKTOP --rate $DESKTOP_RATE --same-as $LAPTOP
        ;;
    desktop)
	xrandr --output $DESKTOP --primary --rate $DESKTOP_RATE --mode $DESKTOP_RES --pos 0x0 --rotate normal --output $LAPTOP --off
        ;;
    dual)
	xrandr --output $DESKTOP --primary --rate $DESKTOP_RATE --mode $DESKTOP_RES --pos 0x0 --rotate normal --output $LAPTOP --mode $LAPTOP_RES --pos ${DESKTOP_RES:0:4}x0 --rotate normal 
        ;;
    laptop)
	xrandr --output $LAPTOP --primary --mode $LAPTOP_RES --pos 0x0 --rotate normal --output $DESKTOP --off 
	;;
    *)
        echo "== ! screenlayout : missing or invalid argument ! =="
        echo "Try again with: clone | desktop | dual | laptop"
        exit 2
esac

nitrogen --restore

exit 0
