#!/bin/sh
LAPTOP="eDP-1"
DESKTOP="DP-3"
case "$1" in
    clone)
	xrandr --output $LAPTOP --primary --output $DESKTOP --same-as $LAPTOP
        ;;
    desktop)
	xrandr --output $DESKTOP --primary --mode 1920x1200 --pos 0x0 --rotate normal --output $LAPTOP --off --output DP2 --off
        ;;
    dual)
	xrandr --output $DESKTOP --primary --mode 1920x1200 --pos 0x0 --rotate normal --output $LAPTOP --mode 1680x1050 --pos 1920x0 --rotate normal 
        ;;
    laptop)
	xrandr --output $LAPTOP --primary --mode 1680x1050 --pos 0x0 --rotate normal --output $DESKTOP --off 
	;;
    *)
        echo "== ! screenlayout : missing or invalid argument ! =="
        echo "Try again with: clone | desktop | dual | laptop"
        exit 2
esac

nitrogen --restore

exit 0
